spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test1?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: zzzzzwx

server:
  port: 8081
logging:
  level:
    com.zwx: info
    org.springframework: warn
  file:
    name: log/blog-pro.log

mybatis:
  type-aliases-package: com.zwx.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
